name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Обновлено до v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Обновлено до v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf libtool pkg-config zlib1g-dev
          pip install buildozer cython==0.29.32

      - name: Build APK
        run: |
          buildozer android debug
          mv bin/*.apk .

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Обновлено до v4
        with:
          name: encryptednotes-apk
          path: "*.apk"
